#!/usr/bin/env php
<?php

function execute($consolePath)
{
    array_shift($argv);
    $escapedArgs = array_map(function($arg){ return escapeshellcmd($arg); }, $argv);
    passthru('php ' . $consolePath . ' ' . implode(' ' , $escapedArgs));
}

if (file_exists('app/console')) {
    execute('app/console');
} elseif (file_exists('bin/console')) {
    execute('bin/console');
} else {
    $STDERR = fopen('php://stderr', 'w+');
    fwrite($STDERR, "You must be in a symfony project to execute this command.\n");
    exit(1);
}