#!/usr/bin/env php
<?php

	if (file_exists(getcwd() . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'console')) {
		array_shift($argv);
		$escapedArgs = array_map(function($arg){ return escapeshellcmd($arg); }, $argv);
		passthru('php app/console ' . implode(' ' , $escapedArgs));
	} else {
		echo "You must be in a symfony project to execute this command.\n";
	}