#!/usr/bin/env php
<?php

require file_exists(__DIR__.'/vendor/autoload.php')
    ? __DIR__.'/vendor/autoload.php'
    : __DIR__.'/../../autoload.php';

$appVersion = '0.0.3-DEV';

$app = new Symfony\Component\Console\Application('Symfony Installer', $appVersion);
$app->add(new Symfony\Installer\AboutCommand($appVersion));
$app->add(new Symfony\Installer\NewCommand());
$app->add(new Symfony\Installer\SelfUpdateCommand());

$app->setDefaultCommand('about');

$app->run();
