#!/usr/bin/env php
<?php

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    }
}

if (
    (!$classLoader = includeIfExists(__DIR__.'/vendor/autoload.php')) &&
    (!$classLoader = includeIfExists(__DIR__.'/../../autoload.php'))
) {
    $message = <<<EOL
You must set up the project dependencies, run the following commands:

  curl -sS https://getcomposer.org/installer | php
  php composer.phar install


EOL;

    file_put_contents('php://stderr', $message, FILE_APPEND);
    exit(1);
}

$appVersion = '1.0';

$app = new Symfony\Component\Console\Application('Symfony Installer', $appVersion);
$app->add(new Symfony\Installer\AboutCommand($appVersion));
$app->add(new Symfony\Installer\NewCommand());

$app->setDefaultCommand('about');

$app->run();
